spring.application.name=trustrent api

# Database Connection (Ha tuza khara database aahe)
spring.datasource.url=jdbc:postgresql://localhost:5433/trustrent_db
spring.datasource.username=postgres
spring.datasource.password=Anway1234

# Hibernate Settings (He aapoap tables banvel)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Image Upload Data Limit
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# Hi line juna table delete karun navin banvel (Schema mismatch fix karnyasti)
spring.jpa.hibernate.ddl-auto=update
